tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

tap "sj14/tap"

brew "ack"
brew "bat"
brew "diff-so-fancy"
brew "docker"
brew "docker-compose"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "sj14/tap/epoch"
brew "zoxide"

cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "iterm2"
cask "raycast"
